# Image Processing Config <https://gohugo.io/content-management/image-processing/#image-processing-config>

# Default resample filter used for resizing <https://github.com/disintegration/imaging>
resampleFilter: 'box'
# Default JPEG quality setting. Default is 75
quality: 75
# Anchor used when cropping pictures <https://github.com/muesli/smartcrop>
anchor: 'smart'
# Default background color. Hugo will preserve transparency for target formats that supports it
bgColor: '#282b2f'
exif:
  # Regexp matching the fields you want to Exclude from the (massive) set of Exif info available
  includeFields: ''
  # Regexp matching the Exif fields you want to exclude. This may be easier to use than IncludeFields above,
  # depending on what you want
  excludeFields: '.*'
  # Hugo extracts the "photo taken" date/time into `.Date` by default. Set this to true to turn it off
  disableDate: true
  # Hugo extracts the "photo taken where" (GPS latitude and longitude) into `.Long` and `.Lat`. Set this to
  # true to turn it off
  disableLatLong: true
