ru:
  languageName: Russian
  weight: 1
  menu:
    main:
      - identifier: home
        name: Главная
        url: /
        weight: -100
        params:
          icon: home

en:
  languageName: English
  weight: 2
  menu:
    main:
      - identifier: home
        name: Home
        url: /
        weight: -100
        params:
          icon: home
