# Configure Minify <https://gohugo.io/getting-started/configuration/#configure-minify>

disableCSS: false
disableHTML: false
disableJS: false
disableJSON: false
disableSVG: false
disableXML: false
minifyOutput: true

tdewolff:
  css:
    decimals: -1
    keepCSS2: true
  html:
    keepConditionalComments: false
    keepDefaultAttrVals: true
    keepDocumentTags: true
    keepEndTags: true
    keepWhitespace: false
  js: {}
  json: {}
  svg:
    decimals: -1
  xml:
    keepWhitespace: false
