# <>

author: Paramtamtam
Subtitle: Авторский блог об IT и прочей х**не
utteranc_repo_name: 'tarampampam/blog'
utteranc_issue_term: 'pathname'
edit_files_base_uri: 'https://github.com/tarampampam/blog/edit/master/'
copyright: 'Make love, not war'
