# Rules page: <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md>
default: true # includes/excludes all rules by default

# Line length <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013>
MD013: false

# Dollar signs used before commands without showing output <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md014>
MD014: false

## Headings should be surrounded by blank lines <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md022>
#MD022: false

# Multiple headings with the same content <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md024>
MD024: false

# Blank line inside blockquote <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md028>
MD028: false

## Inline HTML <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md033>
#MD033:
#  allowed_elements:
#    - 'a'
#    - 'div'
#    - 'img'
#    - 'br'
#
## First line in file should be a top level heading <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md041>
#MD041: false
