# Configuration docs: <https://gohugo.io/getting-started/configuration/>

languageCode: ru
defaultContentLanguage: ru
enableRobotsTXT: true
removePathAccents: true
#uglyURLs: true
pluralizeListTitles: false
#disableLiveReload: true
enableEmoji: true
disableHugoGeneratorInject: true
title: 'blog [dot] hook'
copyright: Make love, not war
theme: hugo-paper # https://github.com/nanxiaobei/hugo-paper/
sectionPagesMenu: "main"

params:
  author: Paramtamtam
  Subtitle: Авторский блог об IT и прочей х**не
  utteranc_repo_name: 'tarampampam/blog'
  utteranc_issue_term: 'pathname'

languages:
  ru:
    languageName: Russian
    weight: 1
  en:
    languageName: English
    weight: 2

outputFormats:
  RSS:
    baseName: 'rss'
