# Configuration docs: <https://gohugo.io/getting-started/configuration/>

# Disable automatic live reloading of browser window
disableLiveReload: false

# The editor to use when creating new content
newContentEditor: ''

# Enable verbose output
verboseLog: true
