# Configuration docs: <https://gohugo.io/getting-started/configuration/>

# Disable automatic live reloading of browser window
disableLiveReload: false

# Enable `.GitInfo` object for each page (if the Hugo site is versioned by Git).
# This will then update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo: true # disable if build becomes relatively slow

# The editor to use when creating new content
newContentEditor: ''

# Enable verbose output
verboseLog: true
