# Configure Related Content
# <https://gohugo.io/content-management/related/#configure-related-content>

threshold: 80
includeNewer: false
toLower: false
indices:
  - name: keywords
    weight: 100
  - name: date
    weight: 10
