# Configuration docs: <https://gohugo.io/getting-started/configuration/>

# Enable `.GitInfo` object for each page (if the Hugo site is versioned by Git).
# This will then update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo: true
