name: publish

on:
  push:
    branches: [master]
    tags-ignore: ['**']

env:
  BASE_URL: 'https://blog.hook.sh/'
  HUGO_VERSION: '0.71.0'

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  build:
    name: Build content
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build
        run: docker run --rm -v "$(pwd):/src:rw" "tarampampam/hugo:$HUGO_VERSION" --baseURL "$BASE_URL" --noChmod --noTimes

      - name: Upload content
        uses: actions/upload-artifact@v2
        with:
          name: content
          path: public/

  publish:
    name: Publish content
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: gh-pages

      - name: Download content
        uses: actions/download-artifact@v2
        with:
          name: content

      - name: Setup git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email 'actions@github.com'
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"

      - name: Stage changes
        run: git add .

      - name: Commit changes
        run: git commit -m "Deploying ${GITHUB_SHA} to Github Pages"

      - name: Push changes
        run: git push github --force
