name: test

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:

env:
  HUGO_VERSION: '0.56.0'

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Execute misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: 'US'
          pattern: '*.md'
          level: warning
          ignore: routeros
          exclude: '.git/*'

  build:
    name: Try to build
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build
        run: docker run --rm -v "$(pwd):/src:rw" "tarampampam/hugo:$HUGO_VERSION" --baseURL "$BASE_URL" --noChmod --noTimes

  lint-markdown:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Execute linter
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: '**.md'
