name: tests

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  #pull_request: {}

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
#  spellcheck:
#    name: Spell Check
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Check out sources
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#
#      - name: Execute misspell
#        uses: reviewdog/action-misspell@v1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          locale: 'US'
#          pattern: '*.md'
#          level: warning
#          ignore: routeros
#          exclude: '.git/*'

  build:
    name: Build the site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with: {hugo-version: 0.83.1, extended: true}

      - name: Build
        run: hugo --environment production --i18n-warnings --noChmod --noTimes --baseURL "http://127.0.0.1:8080" --destination ./dist

      - name: Pack files
        run: tar -zcf ./dist.tar.gz ./dist

      - uses: actions/upload-artifact@v2
        with:
          name: content
          path: dist.tar.gz
          retention-days: 1

  check-for-broken-links:
    name: Check site for broken links
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with: {name: content, path: .artifact}

      - working-directory: .artifact
        run: tar -xf ./dist.tar.gz -C ./..

      - run: ls -la

#      - uses: gaurav-nelson/github-action-markdown-link-check@v1
#        with:
#          folder-path: .

#  lint-markdown:
#    name: Lint markdown files
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#
#      - name: Execute linter # Docs: <https://github.com/avto-dev/markdown-lint>
#        uses: docker://avtodev/markdown-lint:v1
#        with:
#          args: '**/*.md'
