name: tests

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  #pull_request: {}

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  build:
    name: Build the site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with: {hugo-version: 0.83.1, extended: true}

      - name: Build
        run: hugo --environment production --i18n-warnings --noChmod --noTimes
