name: tests

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  #pull_request:

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
#  spellcheck:
#    name: Spell Check
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Check out sources
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#
#      - name: Execute misspell
#        uses: reviewdog/action-misspell@v1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          locale: 'US'
#          pattern: '*.md'
#          level: warning
#          ignore: routeros
#          exclude: '.git/*'

  build:
    name: Try to build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.83.1
          extended: true

      - name: Build
        run: hugo --environment production --i18n-warnings --noChmod --noTimes --print-mem

#  lint-markdown:
#    name: Lint markdown files
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 1
#
#      - name: Execute linter # Docs: <https://github.com/avto-dev/markdown-lint>
#        uses: docker://avtodev/markdown-lint:v1
#        with:
#          args: '**/*.md'
